approach_planner:
  planning_groups: # Sorted by order of preference
    - first_arm
    - second_arm

  exclude_from_planning_joints:
    - first_artifice
    - second_artifice

  joint_tolerance: 0.01
  skip_planning_approach_vel: 0.5
